sara_gripper_action_controller:
  type: "position_controllers/GripperActionController"
  joint: right_finger_joint
  goal_tolerance: 0.005
  stall_timeout: 2.5
  publish_rate: 50               # default: 50