sara_mecanum_base_controller:
  type: "wm_mecanum_base_controller/WMMecanumBaseController"
  publish_rate: 50               # default: 50
  x_wheel_to_center: 0.2056310
  y_wheel_to_center: 0.22735
  wheel_radius: 0.075
  gb_ratio: 0.033
  lin_max_vel: 1.0
  ang_max_vel: 1.0
  front_left_wheel_joint: "front_left_mecanum_wheel_joint"
  front_right_wheel_joint: "front_right_mecanum_wheel_joint"
  rear_left_wheel_joint: "rear_left_mecanum_wheel_joint"
  rear_right_wheel_joint: "rear_right_mecanum_wheel_joint"
  cmd_vel_timeout: 0.5
  base_frame: "base_link"
  enable_odom_tf: true
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Limits
  linear:
    has_velocity_limits: true
    min_velocity: -0.5
    max_velocity: 0.5
    has_acceleration_limits: true
    min_acceleration: -1.0
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 5.0

  angular:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: true
    max_acceleration: 1.0
    has_jerk_limits: true
    max_jerk: 10.0

