sara_arm_trajectory_controller:
  type: "velocity_controllers/JointTrajectoryController"
  publish_rate: 50               # default: 50
  joints:
    - front_left_mecanum_wheel_joint
    - front_right_mecanum_wheel_joint
    - rear_left_mecanum_wheel_joint
    - rear_left_mecanum_wheel_joint
