sara_base_mecanum_controller:
  type: "wm_mecanum_base_controller/WMMecanumBaseController"
  publish_rate: 50               # default: 50
  joints:
    - front_left_mecanum_wheel_joint
    - front_right_mecanum_wheel_joint
    - rear_left_mecanum_wheel_joint
    - rear_right_mecanum_wheel_joint
