sara_head_pitch_controller:
  type: velocity_controllers/JointPositionController
  joint: head_pitch_joint
  pid: {p: 3.0,  d: 0.0, i: 0.0, i_clamp: 1}
  publish_rate: 50               # default: 50
sara_head_yaw_controller:
  type: velocity_controllers/JointPositionController
  joint: head_yaw_joint
  pid: {p: 3.0,  d: 0.0, i: 0.0, i_clamp: 1}
  publish_rate: 50               # default: 50
